on:
  push:
    branches:
      - "main"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "**.rs"
      - "**.pest"
      - "CHANGELOG.md"

name: Cargo Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the project
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: "${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: "${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}"
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      # Run cargo test
      - uses: actions-rs/cargo@v1
        with:
          command: test
